Redos saved when saving a file caused an error (#94)
* Added a --clearHistory flag to clear all existing user edit history. Sometimes want to do this when updating a new version in case implementation of bookmarks changes and files go bad

* Removed undefined reference to history in ci_program. This should be defined in prefs

* Removed line that tried to import nonexistant file which caused program to crash on other systems

* Make file history save only if save was successful